### PR TITLE
Mangle buffer name

### LINKED ISSUE #88: `b` is a forbidden name in for loops
In a fresh project from `pushup new` (on commit `dc4b44b`), the following `index.up` cannot be built:

```
^for b:=0; b<10; b++ {
    <p>^b</p>
}
```

Output error:

```text
# example/myproject/build
index.up:2: cannot use b (variable of type int) as type io.Writer in argument to io.WriteString:
	int does not implement io.Writer (missing Write method)
index.up:2: cannot use b (variable of type int) as type io.Writer in argument to printEscaped:
	int does not implement io.Writer (missing Write method)
index.up:3: cannot use b (variable of type int) as type io.Writer in argument to io.WriteString:
	int does not implement io.Writer (missing Write method)
build command: building project: building project main executable: exit status 2
```

Changing the variable name to `a` or `i` builds fine.

Observed on a MacBook Pro 2021 (M1 Pro) with macOS 13.1.

### PR DESCRIPTION
**Pull request by llimllib**
rather than preventing users from using the name 'b', let's mangle our own names to something they're unlikely to want to use.

Generated code, before:

```go
			b := new(bytes.Buffer)
//line dump.up:2
			io.WriteString(b, "\n\n")
//line dump.up:3
			io.WriteString(b, "<h2>")
//line dump.up:3
			io.WriteString(b, "Dump request headers")
//line dump.up:3
			io.WriteString(b, "</h2>")
<snip>
			sections["contents"] <- template.HTML(b.String())
```

Generated code, after:

```go
			__pushup_b := new(bytes.Buffer)
//line dump.up:2
			io.WriteString(__pushup_b, "\n\n")
//line dump.up:3
			io.WriteString(__pushup_b, "<h2>")
//line dump.up:3
			io.WriteString(__pushup_b, "Dump request headers")
//line dump.up:3
			io.WriteString(__pushup_b, "</h2>")
<snip>
			sections["contents"] <- template.HTML(__pushup_b.String())
```

- Also fix a few spots where `b` was hardcoded

Fixes #88

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -1666,16 +1666,16 @@ func genCodePage(g *pageCodeGen) ([]byte, error) {
 		g.bodyPrintf("  }()\n")
 		g.used("bytes", "html/template")
 		save := g.ioWriterVar
-		g.ioWriterVar = "b"
+		g.ioWriterVar = "__pushup_b"
```
Comment (paulsmith) [inline main.go:1669]: We should probably document this (there are some other collisions possible, too), but this is definitely making it less likely to encounter in practice.

File: main.go [hunk 2]
```diff
@@ -1666,16 +1666,16 @@ func genCodePage(g *pageCodeGen) ([]byte, error) {
...
 		g.bodyPrintf("  %s := new(bytes.Buffer)\n", g.ioWriterVar)
 		g.generate()
-		g.bodyPrintf("  sections[\"contents\"] <- template.HTML(b.String())\n")
+		g.bodyPrintf("  sections[\"contents\"] <- template.HTML(%s.String())\n", g.ioWriterVar)
```
Comment (paulsmith) [inline main.go:1672]: Ah, thanks for catching this.

File: main.go [hunk 3]
```diff
@@ -1689,7 +1689,7 @@ func genCodePage(g *pageCodeGen) ([]byte, error) {
 			g.bodyPrintf("  }()\n")
 			g.bodyPrintf("  %s := new(bytes.Buffer)\n", g.ioWriterVar)
 			g.genNode(block)
-			g.bodyPrintf("  sections[%s] <- template.HTML(b.String())\n", strconv.Quote(name))
+			g.bodyPrintf("  sections[%s] <- template.HTML(%s.String())\n", strconv.Quote(name), g.ioWriterVar)
```
Comment (paulsmith) [inline main.go:1692]: Same!

**Review by paulsmith — APPROVED** [review]
LGTM! Thanks for the speedy fix. :shipit:

File: main.go (hunk 1 above)
Comment (llimllib) [reply main.go:1669]: agreed, I thought about making a full census of prohibited names but figured that could wait for a fix to free up a common one like this
